### ISSUE TITLE
A custom process function

### ISSUE THREAD

**Issue by monolithed** [babel/grunt-babel#10]
Currently there is no information about which files have been translated
Would like to do any custom processing before... (see [grunt-contrib-concat](https://github.com/gruntjs/grunt-contrib-concat) ) like 

```
module.exports = function (grunt) {
	var done = this.async();

	grunt.initConfig({
		6to5: {
			build: {
				files: [{
					expand: true,
					cwd   : 'trunk/',
					dest  : 'cache/trunk/',
					src   : [ '**/*.js' ]
				}]
			},

			process: function (src, path_to_file) {
				grunt.log.write(path_to_file);
				done();

				return src;
			}
		}
	});
};
```

It will be convenient for debugging or custom wrappers.

![1420849930456](https://cloud.githubusercontent.com/assets/803674/5689596/4d77c5a0-9879-11e4-98f0-7d55826f87e5.png)

**Comment by sindresorhus** [comment]
Every task shouldn't have to manually add this. Use a separate task or open a feature request on grunt.
