### ISSUE TITLE
Unmatched file source glob patterns prevent further compilation

### ISSUE THREAD

**Issue by yourcelf** [babel/grunt-babel#12]
If I interpret it correctly, the convention in grunt tasks is to skip unmatched glob patterns given as file sources unless [``nonull``](http://gruntjs.com/configuring-tasks#files) is passed.

In ``grunt-6to5``, an unmatched glob pattern causes processing to stop.  This could be trivially fixed by just [checking ``src`` for undefined](https://github.com/6to5/grunt-6to5/blob/9599f880f05f8472e177334351b4ed1df3ccbe37/tasks/6to5.js#L12) before processing it, if ``nonull`` is unset.  This could prevent unexpected task failures when setting up new projects where the target files don't exist yet, and make it simpler to share configs.

**Comment by sindresorhus** [comment]
Sounds like that should be fixed in grunt instead.
