### ISSUE TITLE
No way to specify multiple files to be output in another directory

### ISSUE THREAD

**Issue by lukeapage** [babel/grunt-babel#23]
There is no way to have options like

```
{
    files: {
        src: "src/*.js"
        dest: "es5/"
    }
}
```

If you use the above it creates a file called es5 and overwrites it with each of the source files, so you are left with the last file to be transformed in a file called es5.

**Comment by lukeapage** [comment]
just seen all the closed issues to use the expand option. my bad.

**Comment by fsbdev** [comment]
please document this, spent way too long looking how to do it

**Comment by kaanozcan** [comment]
+1 on better documentation...

**Comment by alexilyaev** [comment]
Still not documented

**Comment by jchris** [comment]
answer here is ok  https://github.com/babel/grunt-babel/issues/5

```js
files: [{
    expand: true,
    cwd: 'app',
    src: ['**/*.es6.js'],
    dest: 'app',
    ext: '.js'
}]
```

**Comment by porschelau** [comment]
Please doc this

**Comment by vlad-alexandru-ionescu** [comment]
Please doc this

**Comment by sindresorhus** [comment]
> The above is documented in the grunt docs and is common to all grunt tasks. - https://github.com/babel/grunt-babel/issues/5#issuecomment-60824802

Not going to document this just because none of you bothered to read the grunt docs. This is not the place to document every feature of grunt.
