### ISSUE TITLE
Too slow on load

### ISSUE THREAD

**Issue by tucnak** [babel/grunt-babel#28]
I've just got some stats for babel execution and seems that it's too slow on load especially. Shouldn't it take much more time to compile and less time to load?

![image](https://cloud.githubusercontent.com/assets/934682/6982187/8f564dc8-da16-11e4-8a5f-ab9b57fe65e7.png)

These are stats for a single concat'd javascript file (~10kB, 300 lines).

**Comment by sindresorhus** [comment]
The problem is the main package `babel`, not this plugin.

See: https://github.com/babel/babel/issues/626
