### ISSUE TITLE
`arguments` object don't have a Symbol.iterator property

### ISSUE THREAD

**Issue by monolithed** [babel/grunt-babel#29]
```js
// Firefox
void (() => console.log(...arguments))(0, 1); 
// TypeError: arguments[Symbol.iterator] is not a function
```

```js
// Babel
void (() => console.log(...arguments))(0, 1); // 0, 1
```

Problem is that `arguments` object don't have a `Symbol.iterator` property.

http://people.mozilla.org/~jorendorff/es6-draft.html#sec-createunmappedargumentsobject
http://people.mozilla.org/~jorendorff/es6-draft.html#sec-createmappedargumentsobject

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the babel [issue tracker](https://github.com/babel/babel/issues).*

**Comment by monolithed** [comment]
Oh, it's true
