### ISSUE TITLE
Optional 'runtime' not including corejs; require is undefined

### ISSUE THREAD

**Issue by scottfister** [babel/grunt-babel#30]
I am setting the options `optional: ['runtime']` which has the benefits described [here](http://babeljs.io/docs/usage/runtime/). On that page it says the runtime optional transformer does three things, including using the module helpers instead of inline (it does this) but it is not including `core.js`. 

When I run `grunt` the filesize doesn't increase to indicate anything was added (core.js) and I get the error in console `Uncaught ReferenceError: require is not defined`.

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the babel [issue tracker](https://github.com/babel/babel/issues).*
