### ISSUE TITLE
Problem with source map comment at EOF

### ISSUE THREAD

**Issue by DanDeMicco** [babel/grunt-babel#32]
My project is using multiple JS files, most not being compiled by babel (only using 1 for now), but are being ajax'd in and eval'd because of the framework. In order to debug, I have to use: 
//# sourceURL=someFile.js

What this does is put all the eval'd files into 1 file someFile.js which appears in the sources tab under chrome dev tools so it can be debugged.
 
When I include my sources, if the file I am compiling with babel is not the last file to be included in this 'someFile.js', the first line of the next file to be concatenated to the file will be commented out which will cause problems.

For example:
//# sourceMappingURL=event.service.js.map;require([

This causes an error because require is commented out since there is not a \n at the end of the line. It should read:
//# sourceMappingURL=event.service.js.map;
require([

**Comment by sindresorhus** [comment]
Yup, should be a newline there, but it's still an issue with your concatenator which should handle that.
