### ISSUE TITLE
Possible to update babel-core dependency?

### ISSUE THREAD

**Issue by hummlas** [babel/grunt-babel#36]
It seems there has been quite a bit of development going on in core that's not yet available for grunt-babel users. At the time of writing this babel-core is at version 5.6.4 while grunt-babel on uses version 5.0.0.

I'm particularly missing 5.3.0 and 5.3.1 which has references to speed and performance in the changelog :)

**Comment by sebmck** [comment]
See #9. It uses a `^`.

**Comment by eddiemonge** [comment]
`npm up` will update it for you
