### ISSUE TITLE
Adding multi-task support

### ISSUE THREAD

**Issue by PanzerKunst** [babel/grunt-babel#39]
Hi,

I'm wondering if you're considering adding multi-task support?

Sincerely,
Christophe

**Comment by sindresorhus** [comment]
It's all in the docs and code. You could have easily checked.

https://github.com/babel/grunt-babel/blob/a57559656c78caab1b7b8bdd1bc0a34b1c5d29ae/tasks/babel.js#L6

**Comment by PanzerKunst** [comment]
Ok. I must be missing something then. Can you help? This is what I wrote in my Grunt script:

    grunt.initConfig({
        pkg: grunt.file.readJSON("package.json"),

        babel: {
            site: {
                files: {
                    "public/react-site.js": [
                        "javascript/controllers/**/*.react.js"
                    ]
                }
            }
        },
    });
    
    grunt.registerTask("default",  ["babel:site"]);
    
When running the task, this is the output:
    
    Running "babel:site" (babel) task
    Warning: path must be a string  Use --force to continue.

    Aborted due to warnings.

**Comment by sindresorhus** [comment]
Your glob pattern probably didn't match any files. StackOverflow is a better place to ask support questions.

**Comment by PanzerKunst** [comment]
Very true, sorry about that, and thanks for your help!

Strange thing that I didn't get the error when writing the task (and calling it) without target.
