### ISSUE TITLE
Issue with checking EOL-LAST by Eslint

### ISSUE THREAD

**Issue by kubavanzen** [babel/grunt-babel#44]
I have this piece of code
```
  gulp.src(files)
      .pipe($.babel({sourceMap: false}))
      .pipe(reload({stream: true, once: true}))
      .pipe($.eslint(options))
      .pipe($.eslint.format())
      .pipe($.if(!browserSync.active, $.eslint.failAfterError()));
```
and after running gulp task i am receiving this error (no matter what i do with ES6 file) 
```
  error  Newline required at end of file but not found  eol-last
```
I'd like to remind that my file has eol-last. I tried to investigate the problem and i figured out that babel cut off every white-char after last "normal char".

What can you tell me about this issue? Thank you in advance

**Comment by sindresorhus** [comment]
Why would you lint the generated code? That makes no sense. You should lint the source.

**Comment by sindresorhus** [comment]
This is also the grunt task, not the gulp task.
