### ISSUE TITLE
Commit ea524a8 breaks source maps

### ISSUE THREAD

**Issue by mzgol** [babel/grunt-babel#47]
Commit ea524a8d8c4528a3a98128a5875c9872e112ab18 broke my build. I have a file at:
"app/modules/components/base/item-panel/page-view/alto/alto-highlight-fragments.js"
that's transformed to:
"app/.tmp/processed-pre-ng-annotate/modules/components/base/item-panel/page-view/alto/alto-highlight-fragments.js"
to be later passed to [grunt-ng-annotate](https://www.npmjs.com/package/grunt-ng-annotate). Before the mentioned commit I got an inline source map with:
```js
"file": "app/modules/components/base/item-panel/page-view/alto/alto-highlight-fragments.js"
```
and now I just get:
```js
"file": "alto-highlight-fragments.js"
```

My full `grunt-babel` config:
```js
babel:     options: {
        sourceMap: 'inline',
        sourceRoot: path.join(__dirname, '/../../'),
        retainLines: true,
        loose: [
            // Speed up for-of on arrays by not using the iterator directly.
            'es6.forOf',
        ],
    },

    app: {
        files: [
            {
                expand: true,
                src: [
                    'app/app.js',
                    'app/{modules,lib}/**/*.js',
                ],
                rename: function prependTmpProcessed(dest, src) {
                    return src
                        .replace(/^app\/app\.js/, 'app/.tmp/processed-pre-ng-annotate/app.js')
                        .replace(/^app\/modules\//, 'app/.tmp/processed-pre-ng-annotate/modules/')
                        .replace(/^app\/lib\//, 'app/.tmp/processed/lib/');
                },
            },
        ],
    },
},
```

**Comment by mzgol** [comment]
Ping?

**Comment by sindresorhus** [comment]
// @winterbe @luhn @XhmikosR

**Comment by luhn** [comment]
@mzgol, you never state *why* the new behavior is broken; I believe it to be correct.

**Comment by luhn** [comment]
The old behavior was incorrect, the new behavior lines up with the [sourcemap spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/).
