### ISSUE TITLE
Using babel in a development env

### ISSUE THREAD

**Issue by MohhamedRafi** [babel/grunt-babel#51]
So I am new to the whole grunt thing so forgive me and I dont know where to put it but I am wondering how would I use the code in development env. I understand how to use in deployment but I am having trouble using in a development env like localhost.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
