### ISSUE TITLE
Getting `Unknown option: base.module`

### ISSUE THREAD

**Issue by uglymunky** [babel/grunt-babel#55]
Hi, when I add the `modules: 'umd` option I get the a `Unknown option: base.module` error.  When I remove it, everything works fine.

In my Gruntfile:
```
        babel: {
            dist: {
                options: {
                    sourceMap: true
                    , presets: ['es2015']
                    , modules: 'umd'
                }
                , files: {
                    'dist/myfile.js': 'src/myfile.js'
                }
            }
        }
```

I've also tried moving the options object outside of the `dist` sub-task.

Am I doing something wrong here?

**Comment by ccheney** [comment]
Be sure that you're using the proper names for presets/modules:
http://babeljs.io/docs/plugins/preset-es2015/
http://babeljs.io/docs/plugins/transform-es2015-modules-umd/

**Comment by uglymunky** [comment]
Ah, I see.

So I would load the `transform-es2015-modules-umd` plugin instead of setting the module to `umd`?

Something like:

```
        babel: {
            dist: {
                options: {
                    sourceMap: true
                    , presets: ['es2015']
                    , plugins: ['transform-es2015-modules-umd']
                }
                , files: {
                    'dist/myfile.js': 'src/myfile.js'
                }
            }
        }
```

Doing that made it all work and tranform into umd.  Is this because the `transform-es2015-modules-umd` plugin ends up overriding the `transform-es2015-modules-commonjs` from the `es2015` preset?
