### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by valtido** [babel/grunt-babel#56]
I got the following error when trying to run the suggested code on grunt.

```
Running "babel:dist" (babel) task
Warning: Path must be a string. Received undefined Use --force to continue.
```

Any help?

**Comment by erikcore** [comment]
Seeing the same thing. Any progress fixing this?

**Comment by valtido** [comment]
I eventually got it to work ... 

```
babel: {
      options: {
        sourceMap: true,
        presets: ['es2015']
      },
      files: {
        expand: true,
        cwd: 'src',
        ext: '-es6.js',
        src: ['something.js'],
        dest: 'dist/'
      }
    },
```

**Comment by erikcore** [comment]
The problem for me ended up being an incorrect path to my source file. The error message was just super ambiguous.

**Comment by dfenstermaker** [comment]
For what its worth I was having this issue and updated all packages according to this thread https://github.com/webpack/webpack/issues/2463 and it ended up being the html-webpack-plugin not having a filename property. Hope that helps someone!

**Comment by v1rt** [comment]
Thank you @dfenstermaker ! First I upgraded babel-core, it didn't help. Now I added filename property, the error went away :) Where will the value on the filename property we put be used?

**Comment by dfenstermaker** [comment]
@v1rt that should apply to the name of the index.html file, since webpack html plugin is dynamically building that file you can rename it if you so like :)

**Comment by swapnilpatil427** [comment]
upgrade babel-core to 6.10.4

**Comment by 29er** [comment]
I had to downgrade to node 6.11 and upgrade babel-core to "^6.11.4". that was a blast figuring that out
