### ISSUE TITLE
Browserify bundle

### ISSUE THREAD

**Issue by jaydson** [babel/grunt-babel#6]
i was wondering if we can implement @sebmck's [6to5-browserify](https://www.npmjs.org/package/6to5-browserify) on grunt-6to5.
As the grunt-6to5 is a task to facilitate the 6to5's use, for me it makes sense.
Any thoughts?

**Comment by monolithed** [comment]
###### grunt-browserify

```js
{
	options: {
		transform: ['babelify']
	},

	files: {
		'es5.js': 'es6.js'
	}
}
```

Works well for me
