### ISSUE TITLE
Grunt Babel Taking 6 Seconds Per File

### ISSUE THREAD

**Issue by realph** [babel/grunt-babel#61]
I'm trying to use Babel in my grunt build process to transpile my `.js` project files from ES6 to ES5. I have a `watch` task watching my `.js` directory for changes and when changes are detected, I run the `babel` task. 

For some reason though, changing just one `.js` file takes anywhere between 6-10 seconds to complete. I have a feeling it's transpiling the entire project, but I'm not sure. My `Gruntfile.js` looks like this: 

    grunt.initConfig({
      watch: {
        babel: {
          files: ["<%= yeoman.app %>/scripts/**/*.js"],
          tasks: ["babel"]
        },
        livereload: {
          options: {
            livereload: LIVERELOAD_PORT
          },
          files: [
            "{.tmp,<%= yeoman.app %>}/scripts/**/*.js",
          ]
        }
      },
      babel: {
        options: {
          sourceMap: true,
          presets: ['es2015']
        },
        dist: {
          files: [
            {
              expand: true,
              cwd: '<%= yeoman.app %>/scripts/',
              src: ['**/*.js'],
              dest: '.tmp/scripts/'
            }
          ]
        }
      }
    });
    grunt.registerTask("serve", function(target) {
      return grunt.task.run(["watch"]);
    });

When I run `grunt serve` and change a file it logs the execution time:

> Running "babel:dist" (babel) task
>
> Done, without errors.
>
>
> Execution Time (2015-12-01 11:57:54 UTC)
> babel:dist  6.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 6.7s

But when I use `babel-cli` in my terminal, it transpiles in milliseconds, almost instantaneously even:

    babel --presets es2015 script.js --out-file transpiled.js

Surely this is way too long. Am I doing something wrong here.

Any help is appreciated. Thanks in advance!

**Comment by mrmlnc** [comment]
If you're using npm@2 and babel@6, then this problem occurs because of a new modular structure of Babel (a lot of modules are being duplicated and loaded multiple times).

Upgrade to npm 3 or use babel@5 (`npm i grunt-babel@5`).
