### ISSUE TITLE
Unable to use standard grunt files settings

### ISSUE THREAD

**Issue by jamie-sparked** [babel/grunt-babel#62]
I'm integrating react with my project and want to have grunt compile all my jsx sources to js. New sources are being added regularly, so I'm trying to use grunt's wildcard notation.

It's possible I have an unusual configuration, but looking at the source here, using `el.src[0]` appears to be incorrect. I have this in my Gruntfile for babel. It's similar to many of the other sections for things like less and those work fine:

```
			  	files : [
		  	        {
		  	            src  : ['*.jsx'],
		  	            dest : '<%= rr.scripts %>/r/',
		  	            cwd  : '<%= rr.xscripts %>/'
		  	        }
		  	    ]
```

And I added `grunt.log.write(JSON.stringify(el));` at line 12 of babel.js and I see this output:

```
{"src":["Blurb.jsx","Experiment1.jsx","HelloWorld.jsx","IconList.jsx","InputButton.jsx","Popover.jsx","Spinner.jsx","StandardButton.jsx","TBContainer.jsx","TBRow.jsx","TestWidget.jsx","TodoList.jsx"],"dest":"../public/static/js/r/","cwd":"../public/static/jsx/","orig":{"src":["*.jsx"],"dest":"../public/static/js/r/","cwd":"../public/static/jsx/"}}Warning: ENOENT, no such file or directory 'Blurb.jsx' Use --force to continue.
```

Clearly, grunt is expecting plugins to iterate over the "src" attribute and join it with the "cwd" attribute. Those are in fact the components I want to compile.

I apologize for not making a test case, but I am not that familiar with node development. I could probably manage to make a patch for this and test it against my use case if it would help.

**Comment by sindresorhus** [comment]
Per grunt docs, you have to use the `expand` option.
