### ISSUE TITLE
No minimatch support?

### ISSUE THREAD

**Issue by onury** [babel/grunt-babel#67]
I have a deep directory structure. I cannot add each file one by one. Why don't you make use of the [minimatch](https://github.com/isaacs/minimatch) library which is already supported by Grunt?

```
grunt.initConfig({
        babel: {
            options: {
                sourceMap: true,
                presets: ['es2015']
            },
            dist: {
                files: {
                    'build/**/*.js': 'src/**/*.js'  // <-- doesn't work
                }
            }
        }
    });
```

**Comment by sindresorhus** [comment]
Use the `expand` option. https://github.com/babel/grunt-babel/pull/66/files
