### ISSUE TITLE
If you want grunt-babel work, You mast creat a file .babelrc

### ISSUE THREAD

**Issue by woaixiangbao** [babel/grunt-babel#69]
In the README,there isn't say must creat a file .babelrc.

so,when I run grunt ,it dose not work.

I ask google,they say, you must create a file name .babelrc,and in the file you must write these:

```
{
  'presets':['es2015']
}
```

Finally, it works!

Please upload the README

**Comment by sindresorhus** [comment]
Can't reproduce. The gruntfile example in the readme is exactly what's used in the tests. Submit a failing test if this is actually an issue.
