### ISSUE TITLE
use peerDependency instead of dependency to target babel-core

### ISSUE THREAD

**Issue by ohjames** [babel/grunt-babel#74]
This would let me install my own version of babel instead of being forced to use whichever one grunt-babel has bundled.

For example right now the latest grunt-babel release in the npm registry has a very old version of babel.

**Comment by sindresorhus** [comment]
You can already do that. Just depend on a specific Babel version yourself and npm@3 will deduplicate to that one. This plugin already installs the latest version of Babel. I'd suggest reading about how Semver works: https://nodesource.com/blog/semver-tilde-and-caret
