### ISSUE TITLE
Babel 7 Stable Version Released

### ISSUE THREAD

**Issue by Sibiraj-S** [babel/grunt-babel#94]
Babel 7 stable version is released. There is a `8.0.0-beta.0` which supports babel 7. Expecting a stable release.

Also check #93, which updates dependencies for babel to stable version, 
which drops support for nodejs-4 and added nodejs-10. as babel dropped its support

**Comment by Sibiraj-S** [comment]
@loganfsmyth Can you check this too.

**Comment by Sibiraj-S** [comment]
valid point. but I think both are equally used out there. In my view, I prefer grunt when I write custom tasks.

**Comment by loganfsmyth** [comment]
It's alright for now. Can you verify for me that `8.0.0-beta.1` works well for you?

**Comment by Sibiraj-S** [comment]
Yes. Works like charm.

**Comment by loganfsmyth** [comment]
Released: https://github.com/babel/grunt-babel/releases/tag/v8.0.0
