### ISSUE TITLE
Using removed Babel 6 option: .sourceMapTarget

### ISSUE THREAD

**Issue by rielmedia** [babel/grunt-babel#98]
**Setup:**

- Windows 10
- node 10.14.1
- npm 5.8.0
- npx 5.8.0

I have a Wordpress site with **npm** installed locally.  I also have **@babel/core**, **@babel/register**, **@babel/presets-env** installed.  I am trying to use Grunt Babel to compile the JavaScript in a custom Wordpress plugin but when I run `grunt` I get the following warning:

```
Using removed Babel 6 option: .sourceMapTarget - The `sourceMapTarget` option has been removed because it makes more sense for the tooling that calls Babel to assign `map.file` themselves. Use --force to continue.
```  

Here is the babel configuration from my:

**Gruntfile.js**
```
babel: {
   options: {
        sourceMap: true,
   },
   dist: {
       files: {
          'wp-content/plugins/grass-huggers-api/js/main.js': 'wp-content/plugins/grass-huggers-api/js/src/**/*.js',
       },
   },
},
```

**.babelrc**
```
{
  "presets": ["@babel/preset-env"]
}
```

How do I fix this?

**Comment by nocarroll** [comment]
I was experiencing this issue with `grunt-babel 7.0.0`, and updating to `8.0.0` resolved the warning.
